-- CreateTable
CREATE TABLE "baptism_records" (
    "id" SERIAL NOT NULL,
    "serial_number" INTEGER,
    "date_of_baptism" TIMESTAMP(3),
    "baptism_name" TEXT,
    "other_names" TEXT,
    "surname" TEXT,
    "date_of_birth" TIMESTAMP(3),
    "place_of_baptism" TEXT,
    "home_town" TEXT,
    "fathers_name" TEXT,
    "mothers_name" TEXT,
    "solemn_or_private" TEXT,
    "name_of_god_parents" TEXT,
    "name_of_minister" TEXT,
    "first_holy_communion_date" TIMESTAMP(3),
    "first_holy_communion_place" TEXT,
    "first_holy_communion_minister" TEXT,
    "confirmation_date" TIMESTAMP(3),
    "confirmation_place" TEXT,
    "confirmation_minister" TEXT,
    "marriage_date" TIMESTAMP(3),
    "marriage_partner_name" TEXT,
    "marriage_place" TEXT,
    "marriage_witnesses" TEXT,
    "marriage_minister" TEXT,
    "date_of_death" TIMESTAMP(3),
    "remarks" TEXT,
    "extra_field_1" TEXT,
    "extra_field_2" DOUBLE PRECISION,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "baptism_records_pkey" PRIMARY KEY ("id")
);
